### PR TITLE
checklist dependency definition added

### PR DESCRIPTION
**Pull request by munjaldevelopment**
### BEFORE - User Role & permission was showing different earlier

??

### AFTER - will show Role / permission as Checklist dependency

??

### You can check that from checkout using this branch & "crud" repo with "default-field-value" branch.

### CODE REVIEW

**Comment by tabacitu** [comment]
@munjaldevelopment - I don't understand what this does and why it's needed... could you please rephrase? Or add a screenshot?...

**Comment by tabacitu** [comment]
OOOOHH... so what this does... is: **use the new "checklist dependency" column on the Users CRUD**. Correct?

Ok... let's work on wording a little bit @munjaldevelopment . Clean up your mind - you're not you, you're me, someone who has no idea what this PR does. Go through the PR name and description. Is there any way to understand that, from the title/content? 😀 

This is obviously not necessary _now that I understand_, but **please take a moment to reword the title and description**. Try to make it clear what this PR does. It's very important for collaboration to communicate clearly, and this exercise will help set the standard for the next PRs. Also, please don't edit the headlines. Your answers to the headings would look so much better if they were in normal text, not headline.

Sorry to be so pretentious about this, but I cannot stress enough how important good communication is. Have you read [The Whole Fruit Manifesto](https://github.com/the-whole-fruit/manifesto) as we asked?

**Comment by munjaldevelopment** [comment]
Understood @Cristian Tabacitu ***@***.***>  I
didn't change the title & description. May be I need to explain more what I
have done?

https://github.com/the-whole-fruit/manifesto Thanks for sharing this. I got
the idea now.

**Comment by tabacitu** [comment]
Yes, that's what I'm saying 😀

**Comment by munjaldevelopment** [comment]
I will share document soon.

**Comment by munjaldevelopment** [comment]
"Role/Permission" individual column commented & combined "checklist_dependency" to show "Roles & Permission"

**Pull request merged**
