### PR TITLE
spatie/laravel-permission bump from ^1.4 to ^2.7 (breaking change)

### PR DESCRIPTION
**Pull request by tomsb**
Upgraded because I needed this: [spatie/laravel-permission#using-multiple-guards](https://github.com/spatie/laravel-permission/tree/2.7.6#using-multiple-guards).

- Updated migrations file from spatie/laravel-permission
- Updated models (added table fields that are new in new migration file)

It works as expected in fresh backapack+PermissionManager install.

### CODE REVIEW

**Comment by lloy0076** [comment]
Wouldn't it be better to improve #118?

**Comment by pavoltanuska** [comment]
Any update here?

I'm using a custom guard (as always) and since PermissionManager is outdated I have two choices now:

- implement `spatie/laravel-permission` in latest version (2.9.*) for our project only (without PermissionManager)
- do it with PermissionManager updated to latest `spatie/laravel-permission` version (which would be the prefered solution)

So, I'm offering my help to speed things up. @tabacitu is there anything I can do to move this forward?

**Comment by JustJeremy** [comment]
So when will this be upgraded to the latest spatie?  Right now this has basically broken my whole project.  In your version you can't use any operators like | to check for multiple roles. This issue has been fixed by spatie.  I did try to upgrade just the spatie but it broke the whole project. Multiple issues with backpack as well as the calls to stuff like hasrole...etc.   At this point I'm almost regretting going with backpack.  I've spent about 700 hours on this application  and most of that built upon backpack and other laravel packages that are constantly being updated.  Yes, I see you are updating backpack but none of the packages it relies on.  There has to be a better way to keep the packages you use up to date as well as doing the backpack updates.

**Comment by tabacitu** [comment]
Hi guys,

Sorry it took so much time to solve this. Always something important to solve in the big packages, and this one "worked". 

The big problem is indeed the upgrade process. ```spatie/laravel-permission``` doesn't provide an upgrade guide, not even for major versions, and they push breaking changes like crazy, even in patch and minor versions, so it's very difficult to always support the latest version, without breaking people's apps. So far the safe choice has been to just not update it, but it's been too long since an update.

I'm on it, though, and I'll figure out a way to solve this today.
Cheers!

**Comment by tabacitu** [comment]
@tomsb I totally understand your frustration and I think you're right - things have NOT been going well in maintaining this package. And LangFileManager, I could add. I just couldn't find enough time to maintain all packages, and Base and CRUD took priority. I am totally committed to the success and maintenance of Backpack, that's why I poured my heart, sweat and money into Backpack for the past 2 years. But choosing to release additional packages from Base and CRUD... that might have been a bad decision. Too difficult to maintain all of them. That's why I keep talking about a "package marketplace" - I hope the community will come up with way better packages than I could, and I'll stick to making Base and CRUD better and better.

Right now I'm working on this fix. Better late than never, I suppose. And yours looks like the best, BTW, good job. But I do think we need a more long-term solution, so we never get to a situation like this again.

**Idea:** @Laravel-Backpack/veterans **what do you think about releasing all Backpack packages except Base and CRUD under MIT License?** I am a bit of a control freak - you know that, so I do feel the need to watch each and every commit to master, for Base, CRUD and Generators. But not to the others.

This way:
- I could allow @Laravel-Backpack/veterans to write on master for one project, and see how it goes; if I don't answer for a few days, the community can decide wether to do something or not;
- if someone has a preference for a particular package, they could become a "package chief" or something like that, if they commit to maintaining it;
- if someone doesn't like where one package is going, they can fork it and build their own; say... ```PermissionManager2```, or ```LogManagerPlus``` or ```NewsCrudAdvanced```, stuff like that;
- since these additional packages were never meant to be complete solutions, only the 80/20 that would help you get up-and-running, if anybody likes to create extensive solutions, they can, and they can reuse their code for it; but I personally would prefer simple packages; I vote _building bottoms-up vs top-down_, every time;

What do you guys think? Good idea or it won't work? Should we start with one project and see how it goes? Does anybody have special feelings for one of the additional packages and would like to own it?

**Comment by tabacitu** [comment]
@tomsb thanks a lot, I've just merged, polished and pushed it in this PR here https://github.com/Laravel-Backpack/PermissionManager/pull/155

Cheers!

**Pull request merged**
