### PR TITLE
Update User model on migrations for Laravel 8

### PR DESCRIPTION
**Pull request by dauvray**
User model moved to Models folder in Laravel 8

### CODE REVIEW

**Comment by promatik** [comment]
I was thinking if we should create another migration for this, generally it's bad idea to change migrations.
But in this case, it makes sense to provide this change as soon as possible, it do not affect old users who migrated already to Laravel 8 because when doing it they may have done this migration already.

However, I'm wondering if this is a braking change, since one can update permission manager, and run the migration, without updating Laravel to v8 🤔
Anyway, not doing this is keeping a problem to those who update to Laravel 8.

I approve the merge since it covers most of the use cases, if one's updating permission manager, probably is updating everything 🤷‍♂️

**Review by promatik — APPROVED** [review]

**Comment by tabacitu** [comment]
Thanks guys! I agree with @promatik - we definitely shouldn't change existing migrations.

We could/should add a new migration for this. But it's a tricky one, because the migration should only be run if the dev moved his user model from `App\User` to `App\Models\Users`. But then again, the [Laravel 8 Upgrade Guide](https://laravel.com/docs/8.x/upgrade) does not instruct you to do that. So I don't think we should assume people will do that. Perhaps rather than including a migration which will be run automatically, we add a step in the upgrade instructions, with the migration, so that people who DID move their user model can create and run it?!

**Review by tabacitu — CHANGES_REQUESTED** [review]
I don't think this is safe to do. By changing the existing migration we risk leaving behind the people who have already run it.

**Comment by tabacitu** [comment]
For this purpose, let's close this issue in favour of #262 - I think documentation would be a better fix for this. But that documentation DOES need to include migration code - thanks @dauvray !

**Pull request closed without merging**
