### PR TITLE
Correct en translation and Add Simplified Chinese translation

### PR DESCRIPTION
**Pull request by kiddtang**
- Found a trivial capital typo in the English language file
- Added Simplified Chinese language file

### CODE REVIEW

**Comment by pxpm** [comment]
Hey @kiddtang ! Hope you are doing well. 

Thanks for the chinese translation and also for the capitalization! I wouldn't have noticed because we capitalize it on the blade file:

https://github.com/Laravel-Backpack/CRUD/blob/239e60df0436f8a817facce20a2dffcb2b6e7250/src/resources/views/crud/list.blade.php#L17

🙃 

I checked one or two words it seems fine
image

I will be marking this ready to merge. 

Wish you the best,
Pedro

**Review by pxpm — APPROVED** [review]
👍

**Comment by kiddtang** [comment]
> Hey @kiddtang ! Hope you are doing well.
> 
> Thanks for the chinese translation and also for the capitalization! I wouldn't have noticed because we capitalize it on the blade file:
> 
> https://github.com/Laravel-Backpack/CRUD/blob/239e60df0436f8a817facce20a2dffcb2b6e7250/src/resources/views/crud/list.blade.php#L17
> 
> 🙃
> 
> I checked one or two words it seems fine
> image
> 
> I will be marking this ready to merge.
> 
> Wish you the best,
> Pedro

Thanks @pxpm !

I notice it from the Create button. 🙃

When the characters can't be simplified, then they will share the same characters.  😅

**Comment by tabacitu** [comment]
Thank you @kiddtang ! 🎉

**Pull request merged**
