### PR TITLE
Update UserCrudController.php

### PR DESCRIPTION
**Pull request by mishbah**
Changed type from `email` to `text` at `email` column (cause `email` column not available)
Removed all `addColumn` method, and move all column to `addColumns` method

### CODE REVIEW

**Comment by OwenMelbz** [comment]
I'm not sure why you're removing the email field?

Yes technically there is not a column type for it, but the waterfall nature of it means that it will use the default text field.

However by leaving it as email allows people to add their own custom email view.

If you force it as text then the user will need to extract the class from the package to be able to have a custom email field type.

Does that make sense?

**Comment by mishbah** [comment]
"If you force it as text then the user will need to extract the class from the package to be able to have a custom email field type."

I just change the column type not the field type. And IMO, for column, text type can handle email, cause email just text

**Comment by OwenMelbz** [comment]
Sure text can be used for email, but by forcing to text, you remove the ability for users to customize it if they wanted.

For example in or project we've added an email column template which turns it into a link.

If we were to accept this PR in its current form. Users would be unable to do this.

Does that make more sense?

**Comment by mishbah** [comment]
"For example in or project we've added an email column template which turns it into a link."

I see..

But if user create email.blade.php at `/resources/views/vendor/backpack/crud/columns` and change email to the link (for example). All the `email` column will change to the link, and I think that is bad idea too

**Comment by tabacitu** [comment]
Hi @OwenMelbz, @mishbah !

My 2 cents: an "email" column that turns the email into a link sounds like the expected behaviour to me. It's so simple and nice, I don't know why we don't already have it :-) I think it would be a great addition to CRUD. If we do that:
- we add a new useful column
- we eliminate the issue @mishbah talked about (column doesn't exist)
- we eliminate the issue @OwenMelbz talked about if we merge this PR (having to extract the class from the package)

What do you guys think? Good solution?

**Comment by OwenMelbz** [comment]
Sure, I can paste our column in when I get to work to see what you think about it

**Comment by tabacitu** [comment]
Hi guys,

Just added the "email" column type to the Backpack\CRUD dev branch -> https://github.com/Laravel-Backpack/CRUD/commit/e3fb03e0a028abfb9425b7e7253a4a68c1668987. As it will be available shortly, I'll close this issue.

@mishbah , thanks a lot for submitting the PR, I'm sorry it didn't get merged this time. But keep 'em coming - this is a very good way to improve Backpack for all of us.

Cheers!

**Pull request closed without merging**
