### PR TITLE
Update package to use Spatie/Laravel-Permission version 2

### PR DESCRIPTION
**Pull request by clarkewing**
I needed to incorporate permission management into a project I'm working on, but was disappointed to see that this package wasn't updated to Laravel-Permission's latest version.

This PR changes a few files to make it well with the few breaking changes in Spatie's updated package.

I also took the liberty of removing the hard coded copies of Spatie's package's config and migration files, and updated the readme accordingly.
It seemed to me like the better way of doing things. IMO it's better for a developer to understand what's going on than for everything to install itself quickly.

Let me know if you consider anything needs changing!

### CODE REVIEW

**Comment by lloy0076** [comment]
This seems to do what #118 purports to do as well _but_ in a different way.

I'm not so sure the removed configuration(s) should be removed.

**Comment by tabacitu** [comment]
Hi guys,

Sorry it took so much time to solve this. Always something important to solve in the big packages, and this one "worked". 

The big problem is indeed the upgrade process. ```spatie/laravel-permission``` doesn't provide an upgrade guide, not even for major versions, and they push breaking changes like crazy, even in patch and minor versions, so it's very difficult to always support the latest version, without breaking people's apps. So far the safe choice has been to just not update it, but it's been too long since an update.

I'm on it, though, and I'll figure out a way to solve this today.
Cheers!

**Comment by tabacitu** [comment]
DONE! We now have support for it - take a look at this PR for more info https://github.com/Laravel-Backpack/PermissionManager/pull/155 and please [read my entire apology and solution here](https://github.com/Laravel-Backpack/PermissionManager/pull/139#issuecomment-395443718). Curious what you guys think.

**Comment by tabacitu** [comment]
@clarkewing - thanks a lot for the PR. Sorry it did not get merged, and it sat this long before we could take it into consideration. Please don't let this stop you from submitting other PRs, they are really _really_ appreciated, it's just bad management on our end.

**Pull request closed without merging**
